import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { randomUUID } from "node:crypto";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";

import { loadApiTypeDefs, refreshModuleRegistryCache } from "../src/subagent/code-act-executor.js";
import { loadModuleRegistry, lookupFullDocs } from "../src/sandbox/modules/module-registry.js";
import { createTelegramClientProxy } from "../src/sandbox/modules/telegram/index.js";
import type { CapabilityRegistryEnv } from "../src/sandbox/capability-registry.js";
import { TelegramAdapter } from "../src/adapter/telegram-adapter.js";
import { NotificationCenter } from "../src/event/notification-center.js";
import type { TelegramConfig } from "../src/core/config.js";

function makeConfig(): TelegramConfig {
    return {
        mode: "userbot",
        botToken: "",
        apiId: "12345",
        apiHash: "hash",
        phone: "+8613800000000",
    };
}

function makeNC(): NotificationCenter {
    return new NotificationCenter(join(tmpdir(), `tg-guides-${randomUUID()}.jsonl`), false);
}

describe("Telegram builtin guides", () => {
    it("keeps one-step APIs visible and exposes guide activators for mtcute domains", () => {
        refreshModuleRegistryCache();
        const brief = loadApiTypeDefs("telegram");

        assert.ok(brief.includes("useInlineBot"));
        assert.ok(brief.includes("useStories"));
        assert.ok(brief.includes("usePolls"));
        assert.ok(brief.includes("useAccountProfile"));
        assert.ok(brief.includes("useChatAdministration"));
        assert.ok(brief.includes("forwardMessage"));
        assert.ok(brief.includes("useMediaDownload"));
        assert.equal(brief.includes("用于转发、复制、评论"), false);
        assert.ok(brief.includes("用于创建投票/测验、读取投票结果等成组流程"));
        assert.ok(brief.includes("downloadMedia"));
        assert.equal(brief.includes("useContacts"), false);
        assert.equal(brief.includes("useBusiness"), false);
        assert.equal(brief.includes("useBotsAndWebApps"), false);
        assert.equal(brief.includes("useChatFolders"), false);
        assert.equal(brief.includes("useStickers"), false);
        assert.equal(brief.includes("useStarsAndGifts"), false);
        assert.equal(brief.includes("useAccountSecurity"), false);
        assert.equal(brief.includes("queryInlineBot("), false);
        assert.equal(brief.includes("sendInlineBotResult("), false);
        assert.equal(brief.includes("sendPoll"), false);
    });

    it("injects full inline bot guide through two-pass docs", () => {
        const docs = lookupFullDocs(loadModuleRegistry(), ["telegram.useInlineBot"]);

        assert.ok(docs.includes("### telegram.useInlineBot"));
        assert.ok(docs.includes("telegram.queryInlineBot"));
        assert.ok(docs.includes("telegram.sendInlineBotResult"));
        assert.equal(docs.includes("#### telegram 相关类型定义"), false);
    });

    it("injects guide docs for account profile methods without typeDefs bloat", () => {
        const docs = lookupFullDocs(loadModuleRegistry(), ["telegram.useAccountProfile"]);

        assert.ok(docs.includes("### telegram.useAccountProfile"));
        assert.ok(docs.includes("AUTO-GENERATED by src/tools/generate-telegram-mtcute-guides.ts"));
        assert.ok(docs.includes("telegram.updateProfile"));
        assert.ok(docs.includes("telegram.setMyUsername"));
        assert.equal(docs.includes("#### telegram 相关类型定义"), false);
    });

    it("uses generated mtcute signatures and referenced TL types for administration guides", () => {
        const docs = lookupFullDocs(loadModuleRegistry(), ["telegram.useChatAdministration"]);

        assert.ok(docs.includes("telegram.restrictChatMember(params: {"));
        assert.ok(docs.includes("restrictions: Omit<tl.RawChatBannedRights, '_' | 'untilDate'>;"));
        assert.ok(docs.includes("passing `sendMessages=true` will disallow the user to send messages"));
        assert.ok(docs.includes("interface RawChatBannedRights {"));
        assert.ok(docs.includes("sendMessages?: boolean;"));
        assert.equal(docs.includes("rights: unknown"), false);
        assert.equal(docs.includes("answerBotGuestChatQuery"), false);
    });

    it("does not inject culled bot/business/account-management mtcute domains", () => {
        const registry = loadModuleRegistry();
        const advanced = lookupFullDocs(registry, ["telegram.useAdvancedMessages"]);

        assert.equal(lookupFullDocs(registry, ["telegram.useBusiness"]), "");
        assert.equal(lookupFullDocs(registry, ["telegram.useBotsAndWebApps"]), "");
        assert.equal(lookupFullDocs(registry, ["telegram.useContacts"]), "");
        assert.equal(advanced.includes("telegram.translateText"), false);
        assert.equal(advanced.includes("telegram.translateMessage"), false);
        assert.equal(advanced.includes("telegram.sendPaidReaction"), false);
        assert.equal(advanced.includes("telegram.searchGlobal"), false);
        assert.equal(advanced.includes("telegram.editInlineMessage"), false);
        assert.equal(advanced.includes("telegram.forwardMessages"), false);
    });

    it("prints guide content when useInlineBot is executed directly", async () => {
        const outputs: string[] = [];
        const env: CapabilityRegistryEnv = {
            ctx: {},
            emitOutput: (line) => outputs.push(line),
            notifyHost: () => {},
            requestInput: async () => "",
            printToHost: (message) => outputs.push(message),
            spawnTask: () => {},
            killTask: () => {},
            listTasks: () => [],
            callHost: async () => {
                throw new Error("guide activator should not call host");
            },
        };

        const telegram = createTelegramClientProxy(env, new Map()) as { useInlineBot(): Promise<string> };
        const guide = await telegram.useInlineBot();

        assert.ok(guide.includes("TelegramGuide: useInlineBot"));
        assert.ok(guide.includes("queryInlineBot"));
        assert.ok(outputs.some(line => line.includes("sendInlineBotResult")));
    });

    it("supports inline bot query and send host calls", async () => {
        const nc = makeNC();
        const calls: Array<Record<string, unknown>> = [];
        const fakeClient = {
            async start() {
                return { id: 99, displayName: "Userbot", isBot: false };
            },
            onNewMessage: { add() {}, remove() {} },
            async resolveUser(peer: unknown) {
                assert.equal(peer, "@gif");
                return { _: "inputUser", userId: 1, accessHash: { low: 2, high: 0, unsigned: false } };
            },
            async resolvePeer(peer: unknown) {
                return { _: "inputPeerChat", chatId: peer };
            },
            async call(request: Record<string, unknown>) {
                calls.push(request);
                if (request._ === "messages.getInlineBotResults") {
                    return {
                        queryId: { low: 123, high: 0, unsigned: false },
                        nextOffset: "",
                        results: [{
                            id: "result-1",
                            type: "article",
                            title: "First result",
                            sendMessage: { _: "botInlineMessageText", message: "hello" },
                        }],
                    };
                }
                return { _: "updates", updates: [] };
            },
            async destroy() {},
        };

        const adapter = new TelegramAdapter(makeConfig(), nc, async () => "", () => {}, async () => fakeClient);
        await adapter.start();

        const queried = await adapter.handleCall("telegram.queryInlineBot", ["@gif", "hello", { peer: "-100" }]) as any;
        assert.equal(queried.queryId, "123");
        assert.equal(queried.results[0].id, "result-1");

        await adapter.handleCall("telegram.sendInlineBotResult", ["-100", queried.queryId, "result-1", { replyTo: 7 }]);

        assert.equal(calls[0]._, "messages.getInlineBotResults");
        assert.equal(calls[1]._, "messages.sendInlineBotResult");
        assert.equal((calls[1].queryId as any).toString(), "123");
        assert.deepEqual(calls[1].replyTo, { _: "inputReplyToMessage", replyToMsgId: 7 });

        await adapter.stop();
        nc.dispose();
    });

    it("supports top-level forwardMessage host calls", async () => {
        const nc = makeNC();
        const calls: Array<Record<string, unknown>> = [];
        const fakeClient = {
            async start() {
                return { id: 99, displayName: "Userbot", isBot: false };
            },
            onNewMessage: { add() {}, remove() {} },
            async resolvePeer(peer: unknown) {
                return `input:${String(peer)}`;
            },
            async forwardMessagesById(params: Record<string, unknown>) {
                calls.push(params);
                const ids = params.messages as number[];
                return ids.map((id) => ({
                    id: id + 1000,
                    text: "",
                    date: new Date("2026-01-02T03:04:05Z"),
                    chat: { id: -200, title: "dest", type: "supergroup" },
                    sender: { id: 99, firstName: "Userbot", isBot: false },
                }));
            },
            async destroy() {},
        };

        const adapter = new TelegramAdapter(makeConfig(), nc, async () => "", () => {}, async () => fakeClient);
        await adapter.start();

        const result = await adapter.handleCall("telegram.forwardMessage", ["-200", "-100", "123", {
            silent: true,
            noAuthor: true,
            toThreadId: "7",
        }]) as any;

        assert.deepEqual(calls, [{
            toChatId: "input:-200",
            fromChatId: "input:-100",
            messages: [123],
            silent: true,
            noAuthor: true,
            toThreadId: 7,
        }]);
        assert.equal(result.id, "1123");
        assert.equal(result.chat.id, "-200");

        await adapter.stop();
        nc.dispose();
    });

    it("exposes forwardMessage as a first-class sandbox proxy method", async () => {
        const outputs: string[] = [];
        const notifications: Array<Record<string, unknown>> = [];
        const hostCalls: Array<{ method: string; args: unknown[] }> = [];
        const env: CapabilityRegistryEnv = {
            ctx: {},
            emitOutput: (line) => outputs.push(line),
            notifyHost: (event) => notifications.push(event as Record<string, unknown>),
            requestInput: async () => "",
            printToHost: (message) => outputs.push(message),
            spawnTask: () => {},
            killTask: () => {},
            listTasks: () => [],
            callHost: async (method, args) => {
                hostCalls.push({ method, args });
                return {
                    id: "77",
                    text: "",
                    date: "2026-01-02T03:04:05.000Z",
                    chat: { id: String(args[0]), type: "supergroup" },
                    sender: { id: "99", isBot: false },
                    isMention: false,
                };
            },
        };

        const telegram = createTelegramClientProxy(env, new Map()) as {
            forwardMessage(toChatId: string, fromChatId: string, messageId: number, opts?: Record<string, unknown>): Promise<any>;
        };
        const sent = await telegram.forwardMessage("-200", "-100", 123, { silent: true });

        assert.deepEqual(hostCalls, [{
            method: "telegram.forwardMessage",
            args: ["-200", "-100", 123, { silent: true }],
        }]);
        assert.ok(sent.date instanceof Date);
        assert.ok(outputs.some(line => line.includes("forwardMessage ok")));
        assert.equal(notifications[0].type, "system.agent_message_sent");
        assert.equal(notifications[0].text, "[forward:-100:123]");
    });

    it("emits sticker mediaInfo even when the host ack omits it", async () => {
        const notifications: Array<Record<string, unknown>> = [];
        const env: CapabilityRegistryEnv = {
            ctx: {},
            emitOutput: () => {},
            notifyHost: (event) => notifications.push(event as Record<string, unknown>),
            requestInput: async () => "",
            printToHost: () => {},
            spawnTask: () => {},
            killTask: () => {},
            listTasks: () => [],
            callHost: async () => ({
                id: "4014",
                text: "",
                date: "2026-05-27T12:17:00.000Z",
                chat: { id: "-1002450361141", type: "supergroup" },
                sender: { id: "99", isBot: false },
                isMention: false,
            }),
        };

        const telegram = createTelegramClientProxy(env, new Map()) as {
            sendSticker(chatId: string, uniqueFileId: string): Promise<any>;
        };
        await telegram.sendSticker("-1002450361141", "AgADdg0AAvE2QVQ");

        assert.equal(notifications[0].type, "system.agent_message_sent");
        assert.equal(notifications[0].text, "[🎭 贴纸: AgADdg0AAvE2QVQ]");
        assert.deepEqual(notifications[0].mediaInfo, {
            type: "sticker",
            fileId: "AgADdg0AAvE2QVQ",
            uniqueFileId: "AgADdg0AAvE2QVQ",
        });
    });

    it("supports guide-only story calls and local media paths", async () => {
        const nc = makeNC();
        const tempDir = join(tmpdir(), `tg-story-${randomUUID()}`);
        mkdirSync(tempDir, { recursive: true });
        const imagePath = join(tempDir, "story.jpg");
        writeFileSync(imagePath, "fake image bytes");

        const storyCalls: Array<Record<string, unknown>> = [];
        const fakeClient = {
            async start() {
                return { id: 99, displayName: "Userbot", isBot: false };
            },
            onNewMessage: { add() {}, remove() {} },
            async canSendStory(peer: unknown) {
                assert.equal(peer, "me");
                return true;
            },
            async sendStory(params: Record<string, unknown>) {
                storyCalls.push(params);
                if (storyCalls.length === 1) {
                    throw new Error("native mtcute failed before fallback");
                }
                return { id: 42, peer: params.peer };
            },
            async destroy() {},
        };

        const adapter = new TelegramAdapter(makeConfig(), nc, async () => "", () => {}, async () => fakeClient);
        try {
            await adapter.start();
            assert.equal(await adapter.handleCall("telegram.canSendStory", ["me"]), true);
            const story = await adapter.handleCall("telegram.sendStory", [{
                media: { type: "photo", file: imagePath },
                caption: "hello story",
            }]) as any;

            assert.equal(story.id, 42);
            assert.equal(storyCalls[0].peer, undefined);
            assert.deepEqual(storyCalls[0].media, {
                type: "photo",
                file: imagePath,
            });
            assert.equal(storyCalls[1].peer, undefined);
            assert.deepEqual(storyCalls[1].media, {
                type: "photo",
                file: `file:${imagePath}`,
            });
        } finally {
            await adapter.stop();
            nc.dispose();
            rmSync(tempDir, { recursive: true, force: true });
        }
    });

    it("forwards guide-only mtcute high-level methods through the generic adapter call", async () => {
        const nc = makeNC();
        const calls: Array<Record<string, unknown>> = [];
        const fakeClient = {
            async start() {
                return { id: 99, displayName: "Userbot", isBot: false };
            },
            onNewMessage: { add() {}, remove() {} },
            async updateProfile(params: Record<string, unknown>) {
                calls.push({ method: "updateProfile", params });
                return { id: 99, bio: params.bio };
            },
            async destroy() {},
        };

        const adapter = new TelegramAdapter(makeConfig(), nc, async () => "", () => {}, async () => fakeClient);
        await adapter.start();
        const result = await adapter.handleCall("telegram.mtcute", ["updateProfile", { bio: "hello" }]) as any;

        assert.deepEqual(calls, [{ method: "updateProfile", params: { bio: "hello" } }]);
        assert.equal(result.bio, "hello");

        await assert.rejects(
            () => adapter.handleCall("telegram.mtcute", ["signIn", {}]),
            /not exposed through built-in guides/,
        );
        await assert.rejects(
            () => adapter.handleCall("telegram.mtcute", ["setGameScore", {}]),
            /not exposed through built-in guides/,
        );
        await assert.rejects(
            () => adapter.handleCall("telegram.mtcute", ["translateText", "hello", "zh"]),
            /not exposed through built-in guides/,
        );
        await assert.rejects(
            () => adapter.handleCall("telegram.mtcute", ["forwardMessagesById", { toChatId: "-100", fromChatId: "-100", messages: [1] }]),
            /not exposed through built-in guides/,
        );
        await assert.rejects(
            () => adapter.handleCall("telegram.mtcute", ["addContact", {}]),
            /not exposed through built-in guides/,
        );

        await adapter.stop();
        nc.dispose();
    });

    it("keeps mtcute passthrough args native first and only rewrites file paths as fallback", async () => {
        const nc = makeNC();
        const mediaDir = join(process.cwd(), "workspace", "media");
        mkdirSync(mediaDir, { recursive: true });
        const fileName = `profile-${randomUUID()}.png`;
        const relativePath = join("media", fileName);
        const absolutePath = join(mediaDir, fileName);
        writeFileSync(absolutePath, "fake image bytes");

        const calls: Array<Record<string, unknown>> = [];
        const fakeClient = {
            async start() {
                return { id: 99, displayName: "Userbot", isBot: false };
            },
            onNewMessage: { add() {}, remove() {} },
            async setMyProfilePhoto(params: Record<string, unknown>) {
                calls.push(params);
                if (calls.length === 1) {
                    throw new Error("native mtcute failed before fallback");
                }
                return { id: "photo-id", media: params.media };
            },
            async destroy() {},
        };

        const adapter = new TelegramAdapter(makeConfig(), nc, async () => "", () => {}, async () => fakeClient);
        try {
            await adapter.start();
            const result = await adapter.handleCall("telegram.mtcute", [
                "setMyProfilePhoto",
                { type: "photo", media: `file:${relativePath}` },
            ]) as any;

            assert.equal(calls[0].media, `file:${relativePath}`);
            assert.equal(calls[1].media, `file:${absolutePath}`);
            assert.equal(result.media, `file:${absolutePath}`);
        } finally {
            await adapter.stop();
            nc.dispose();
            rmSync(absolutePath, { force: true });
        }
    });

    it("does not rewrite mtcute passthrough args when the native call succeeds", async () => {
        const nc = makeNC();
        const calls: Array<Record<string, unknown>> = [];
        const fakeClient = {
            async start() {
                return { id: 99, displayName: "Userbot", isBot: false };
            },
            onNewMessage: { add() {}, remove() {} },
            async setMyProfilePhoto(params: Record<string, unknown>) {
                calls.push(params);
                return { id: "photo-id", media: params.media };
            },
            async destroy() {},
        };

        const adapter = new TelegramAdapter(makeConfig(), nc, async () => "", () => {}, async () => fakeClient);
        try {
            await adapter.start();
            const result = await adapter.handleCall("telegram.mtcute", [
                "setMyProfilePhoto",
                { type: "photo", media: "file:media/native-first.png" },
            ]) as any;

            assert.equal(calls.length, 1);
            assert.equal(calls[0].media, "file:media/native-first.png");
            assert.equal(result.media, "file:media/native-first.png");
        } finally {
            await adapter.stop();
            nc.dispose();
        }
    });

    it("preserves mtcute returned objects as host refs that can be passed back", async () => {
        const nc = makeNC();
        const downloadTargets: unknown[] = [];
        const photoLocation = {
            _: "inputPhotoFileLocation",
            id: "5388905675888467317",
            accessHash: "6223377884992484868",
            fileReference: Buffer.from("file-ref"),
            thumbSize: "c",
        };
        const photo = {
            type: "photo",
            location: photoLocation,
            fileSize: 24714,
            dcId: 2,
            raw: { _: "photo", id: "5388905675888467317", fileReference: Buffer.from("file-ref") },
        };
        const fakeClient = {
            async start() {
                return { id: 99, displayName: "Userbot", isBot: false };
            },
            onNewMessage: { add() {}, remove() {} },
            async getProfilePhotos() {
                return [photo];
            },
            async downloadAsBuffer(location: unknown) {
                downloadTargets.push(location);
                return Buffer.from("avatar");
            },
            async destroy() {},
        };

        const adapter = new TelegramAdapter(makeConfig(), nc, async () => "", () => {}, async () => fakeClient);
        try {
            await adapter.start();
            const photos = await adapter.handleCall("telegram.mtcute", ["getProfilePhotos", 123, { limit: 1 }]) as any[];
            const sandboxPhoto = JSON.parse(JSON.stringify(photos[0]));
            const sandboxLocation = JSON.parse(JSON.stringify(photos[0].location));

            assert.equal(typeof sandboxPhoto.__mtcuteRef, "string");
            assert.equal(typeof sandboxLocation.__mtcuteRef, "string");

            const direct = await adapter.handleCall("telegram.downloadMedia", [sandboxPhoto]) as any;
            const nativePhoto = await adapter.handleCall("telegram.mtcute", ["downloadAsBuffer", sandboxPhoto]) as any;
            const nativeLocation = await adapter.handleCall("telegram.mtcute", ["downloadAsBuffer", sandboxLocation]) as any;

            assert.equal(downloadTargets[0], photo);
            assert.equal(downloadTargets[1], photo);
            assert.equal(downloadTargets[2], photoLocation);
            assert.equal(direct.buffer, Buffer.from("avatar").toString("base64"));
            assert.equal(nativePhoto.buffer, Buffer.from("avatar").toString("base64"));
            assert.equal(nativePhoto.size, Buffer.byteLength("avatar"));
            assert.equal(nativeLocation.buffer, Buffer.from("avatar").toString("base64"));
            assert.equal(nativeLocation.size, Buffer.byteLength("avatar"));
        } finally {
            await adapter.stop();
            nc.dispose();
        }
    });

    it("treats accidental mediaInfo objects as their fileId for downloadMedia", async () => {
        const nc = makeNC();
        const downloadTargets: unknown[] = [];
        const fakeClient = {
            async start() {
                return { id: 99, displayName: "Userbot", isBot: false };
            },
            onNewMessage: { add() {}, remove() {} },
            async downloadAsBuffer(location: unknown) {
                downloadTargets.push(location);
                return Buffer.from("image-bytes");
            },
            async destroy() {},
        };

        const adapter = new TelegramAdapter(makeConfig(), nc, async () => "", () => {}, async () => fakeClient);
        try {
            await adapter.start();

            const result = await adapter.handleCall("telegram.downloadMedia", [{
                type: "photo",
                fileId: "AgAC-media-file-id",
                uniqueFileId: `AQAD-${randomUUID()}`,
                downloadStatus: "too_large",
            }]) as any;

            assert.equal(downloadTargets.length, 1);
            assert.equal(downloadTargets[0], "AgAC-media-file-id");
            assert.equal(result.buffer, Buffer.from("image-bytes").toString("base64"));
            assert.equal(result.size, Buffer.byteLength("image-bytes"));
        } finally {
            await adapter.stop();
            nc.dispose();
        }
    });

    it("rejects missing file: mtcute media before the client can create a read stream", async () => {
        const nc = makeNC();
        const calls: Array<Record<string, unknown>> = [];
        const fakeClient = {
            async start() {
                return { id: 99, displayName: "Userbot", isBot: false };
            },
            onNewMessage: { add() {}, remove() {} },
            async setMyProfilePhoto(params: Record<string, unknown>) {
                calls.push(params);
                throw new Error("native mtcute failed before fallback");
            },
            async destroy() {},
        };

        const adapter = new TelegramAdapter(makeConfig(), nc, async () => "", () => {}, async () => fakeClient);
        try {
            await adapter.start();
            await assert.rejects(
                () => adapter.handleCall("telegram.mtcute", [
                    "setMyProfilePhoto",
                    { type: "photo", media: "file:media/definitely-missing-profile-photo.png" },
                ]),
                /mtcute 文件不存在/,
            );
            assert.equal(calls.length, 1);
            assert.equal(calls[0].media, "file:media/definitely-missing-profile-photo.png");
        } finally {
            await adapter.stop();
            nc.dispose();
        }
    });
});
